### PR TITLE
Introducing viz_rd function

### PR DESCRIPTION
**Pull request by darh78**
Hello @BillPetti and @saiemgilani,

Hope everything is OK with both of you.
Congratulations for the release of `baseballr` in CRAN. #

Following Bill's suggestion in this [comment](https://github.com/BillPetti/baseballr/pull/113#issuecomment-575937816), I've now tried to follow the procedure indicated and I'm adding here one of my first functions developed to contribute to this great R package.
Its name is `viz_rd` and it allows to plot the accumulated runs differentials of a team(s) by League or Division (you can see some of the results in this [tweet](https://twitter.com/gmbeisbol/status/1573304838074531840?s=20&t=mGfEXlhbK8bsK-HGXvqXQA)).

I hope that it fits properly into the next release.

Regards.

Daniel.

### CODE REVIEW

**Comment by darh78** [comment]
Hello @saiemgilani, is this pull request accepted?
Thanks

**Comment by saiemgilani** [comment]
My apologies on not making an explicit statement directly here. As of right now, I am not trying to accept any viz related functions to baseballr. It has nothing to do with your code or contribution, but I have been archiving existing viz related functions as well. There are nebulous but currently unpursued plans to try a Plotting package for the @sportsdataverse but I'm afraid we won't get there without someone taking the onus upon themselves.

**Comment by saiemgilani** [comment]
I will say that I think your contributions and vizzes are pretty cool but I wanted to minimize the dependencies to the package since we could very easily run up on the limit.

**Comment by darh78** [comment]
Hello @saiemgilani 

Thanks for your feedback.

Sorry to know that.

In order to understand better the situation, When you say that the function has two dependencies, what do you specifically mean?
If I have the chance to modify the function to remove these "dependencies" but having the same output, would this be an accepted solution?
Or no viz function would fit the 'baseballr' pckg?

On the other hand, in which area of the package would you need or want some contribution?, so I could pursue to develop my R skills with that.

Thanks

Daniel.

**Pull request closed without merging**
