### PR TITLE
get_ncaa_park_factor.R

### PR DESCRIPTION
**Pull request by robert-frey**
This functionality allows you to get any NCAA school's park factor, with adjustments based upon the amount of years that the user decides to choose.

### CODE REVIEW

**Comment by BillPetti** [comment]
Can you tell me more about the adjustments the function makes that gets you to the final park factor?

**Comment by robert-frey** [comment]
Used the adjustment in this article:
https://library.fangraphs.com/park-factors-5-year-regressed/

**Comment by robert-frey** [comment]
The paragraph starting with, "Then we apply regression"

**Comment by BillPetti** [comment]
Ah, got it. So you are using Appelman’s approach but adding .95 for anything over 5 years. Makes sense as a starting point. I’ll merge this soon and test it.

**Comment by BillPetti** [comment]
This looks good, but a few asks:

Can you add some detail around defining what the returned fields are? I think that will be helpful for people when using the function.

Also, I don't see a man file or any updated to the NAMESPACE (I think you are adding functions). Can you generate those? If you don't know how, you need to run `devtools::document()` in the working directory of your fork and that should generate all the needed changes.

**Comment by BillPetti** [comment]
I see two separate pull requests and this function is in both--is this pull request not needed anymore? I want to pull your other one, but wanted to check first.

**Comment by robert-frey** [comment]
Oops, Yes, as long as the function and the updated master_team_lu table is updated.

**Comment by BillPetti** [comment]
merged in another pull request

**Pull request closed without merging**
