### PR TITLE
Updated master_ncaa_team_lu table

### PR DESCRIPTION
**Pull request by robert-frey**
I updated the master_ncaa_team_lu table to include the missing Division 1 schools from 2019.
data/updated_master_ncaa_team_lu.rda

### CODE REVIEW

**Comment by BillPetti** [comment]
Did you just move the 2018 D1 teams and ids forward into 2019?

**Comment by robert-frey** [comment]
Yes, and swapped the conferences of teams that moved conferences, and added North Ala. from D2 to D1. Actually I can send an updated file because there were some more issues I ran into, like Temple not fielding a team in 2015, Akron not fielding a team in either 2015 or 2016, you have some independents that are listed as D1,D2, and D3 in the same year, like Berea (only D3), Rust (only D2), and Palm Beach Atl. (only D2).

**Comment by BillPetti** [comment]
That's weird. I just went with what the NCAA had on their site, so thanks for catching those. FYI, there is some kind of conflict in the NAMESPACE file you may need to fix before I can merge the pull.

**Comment by robert-frey** [comment]
Thanks for letting me know, I will fix it now.

**Pull request merged**
