### PR TITLE
Adjustments to pass R CMD Check

### LINKED ISSUE #2: Imported packages do not appear to be getting attached
```
library(baseballr)   
team_results_bref("NYM",` 2015)
   Error` in team_results_bref("NYM", 2015) : could not find function "%>%"

> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252    LC_MONETARY=English_Canada.1252
[4] LC_NUMERIC=C                    LC_TIME=English_Canada.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] baseballr_0.0.0.9000

loaded via a namespace (and not attached):
[1] rsconnect_0.4.1.11 tools_3.2.2  

```
It ran OK when I loaded dplyr and rvest independently

On a side note, you might want to set the output to a tbl_df for easier handling
Good luck with package

### PR DESCRIPTION
**Pull request by JonathanBob**
* added package `xml2` to description
* imported functions from imported packages via `@importFrom` tag in function descriptions
* replaced non standard evaluation by standard evaluation (`select_` vs `select`, `mutate_` vs. `mutate`, ...)
* deleted examples that didn't work
* set parameters in example for function `standings_on_date_bref`
* set fg_bat_leaders(2015, 2015, 400) example to \dontrun (example takes more than 5 seconds)
* fixed type in line 32 of `daily_pitcher_bref.R`

These adjustments would resolve #2.

### CODE REVIEW

**Comment by BillPetti** [comment]
Can't thank you enough. I've never developed a package before and was fumbling to catch some of these errors.

**Comment by JonathanBob** [comment]
@BillPetti No, thank you. I read your article on [The Hardball Times](http://www.hardballtimes.com/developing-the-baseballr-package-for-r/) and I think this is a great idea for a package.

**Comment by BillPetti** [comment]
Quick question: just tried installing from github to see if the dependencies load now and running into an error:

```
> install_github("BillPetti/baseballr")
Downloading GitHub repo BillPetti/baseballr@master
from URL https://api.github.com/repos/BillPetti/baseballr/zipball/master
Error in eapply(ns_env(pkg), force, all.names = TRUE) : 
  cannot open file '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/baseballr/R/baseballr.rdb': No such file or directory
In addition: Warning message:
In eapply(ns_env(pkg), force, all.names = TRUE) :
  restarting interrupted promise evaluation
```

**Comment by JonathanBob** [comment]
`install_github("BillPetti/baseballr")` works on my machine. But I will search for the problem.

```
> devtools::install_github("BillPetti/baseballR")
Downloading GitHub repo BillPetti/baseballR@master
from URL https://api.github.com/repos/BillPetti/baseballR/zipball/master
Installing baseballr
"C:/PROGRA~1/R/R-32~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  "C:/Users/jbob/AppData/Local/Temp/RtmpG4rLPt/devtools13fc13dc55d0/BillPetti-baseballr-2655aed"  \
  --library="C:/Users/jbob/Documents/R/win-library/3.2" --install-tests 

* installing *source* package 'baseballr' ...
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (baseballr)
Reloading installed baseballr
```

**Comment by BillPetti** [comment]
So, it appears I had some weird issues on my side. Got it to load, and the dependencies seem to be working as well.

```
> install_github("BillPetti/baseballr")
Downloading GitHub repo BillPetti/baseballr@master
from URL https://api.github.com/repos/BillPetti/baseballr/zipball/master
Installing baseballr
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save --no-restore CMD INSTALL  \
  '/private/var/folders/vn/4554mq013jb9bp557lylf7vm0000gn/T/RtmpIW90MY/devtools22fddc89fe4/BillPetti-baseballr-759fc6b'  \
  --library='/Library/Frameworks/R.framework/Versions/3.2/Resources/library' --install-tests 

* installing *source* package ‘baseballr’ ...
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (baseballr)
> require(baseballr)
Loading required package: baseballr

Attaching package: ‘baseballr’

The following objects are masked _by_ ‘.GlobalEnv’:

    daily_batter_bref, daily_pitcher_bref, team_consistency, woba_plus

> head(team_results_bref("NYM", 2015))
  Year Rk Gm#             Date  Tm H_A Opp Result R RA Inn Record Rank   GB        Win      Loss    Save Time D/N Attendance Streak
1 2015  1   1    Monday, Apr 6 NYM   A WSN      W 3  1  NA    1-0    1 Tied      Colon  Scherzer Carlyle 2:35   D      42295      1
2 2015  2   2 Wednesday, Apr 8 NYM   A WSN      L 1  2  NA    1-1    2  1.5 Zimmermann    deGrom  Storen 2:21   N      25999     -1
3 2015  3   3  Thursday, Apr 9 NYM   A WSN      W 6  3  NA    2-1    2  1.0     Harvey Strasburg         2:54   D      25327      1
4 2015  4   4   Friday, Apr 10 NYM   A ATL      L 3  5  NA    2-2    2  2.0    Johnson   Montero  Grilli 3:01   N      46279     -1
5 2015  5   5 Saturday, Apr 11 NYM   A ATL      L 3  5  NA    2-3    3  3.0    Teheran       Gee Johnson 2:25   N      36056     -2
6 2015  6   6   Sunday, Apr 12 NYM   A ATL      W 4  3  NA    3-3    2  2.0      Colon     Jaime Familia 2:37   D      28192      1
```

**Comment by JonathanBob** [comment]
Ok, great

**Comment by BillPetti** [comment]
Darn it, spoke too soon. For some reason it can't find readHTMLTable when running the `team_consistency()` function. I checked the NAMESPACE and the function file itself and I can't see why it wouldn't.

```R
> head(team_consistency(1997))
Error in team_consistency(1997) : could not find function "readHTMLTable"
```

I see `#' @importFrom XML readHTMLTable` in `team_consistency.R` and  `importFrom(XML,readHTMLTable)` in the `NAMESPACE` file from your edits earlier, so not sure what the issue could be.

**Comment by JonathanBob** [comment]
Can't reproduce the error. When I call the `team_consistency` function, R finds `readHTMLTable`. However, there seems to be another problem, as the line

```R
results <- teams %>% group_by_(~Tm, ~year) %>% do_(~scrape_results(Tm, year))
```

does not work (my fault). When working on the package, I only looked for the results from R CMD Check, but didn't call each function.

**Comment by BillPetti** [comment]
So I made a few changes to lines 23:28. Think that fixed it.

**Comment by BillPetti** [comment]
This appears to be an issue on my side. When you get a chance, give the function of whirl based on the updated version and let me know if it's working for you.

**Comment by JonathanBob** [comment]
It works. `readHTMLTable` and `gini` are known and the functions runs without error.

**Comment by BillPetti** [comment]
Awesome. Thanks again for all your help.

**Pull request merged**
