### PR TITLE
attempt at Chadwick installation checks; #307

### PR DESCRIPTION
**Pull request by beanumber**
Grateful for feedback on this PR for #307 !

### CODE REVIEW

**Review by saiemgilani — APPROVED** [review]

**Comment by saiemgilani** [comment]
I'm not really sure if this will work but we will try it on main and get it fixed if there are issues once we really check it

**Comment by beanumber** [comment]
FYI, we are hoping to send the book to the publisher next week. This function is currently not included in the book. (See https://beanumber.github.io/abdwr3e/A_retrosheet.html#sec-chadwick for a function with similar functionality.) However, that could be changed (but only before next week).

**Comment by saiemgilani** [comment]
It's included on the main branch and will be included in the CRAN version assuming the function doesn't get flagged by CRAN for not meeting some requirements

**Comment by beanumber** [comment]
OK, sounds good! Thanks!

**Pull request merged**
